#!/usr/bin/env python3
"""Analyze solving time results from results_ga/.

Produces a summary table (printed + LaTeX) and line plots showing
solve time vs. instance size for the GA solver.  Instances that
timed out (1 h) are shown separately.
"""

import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
RESULTS_DIR = Path(__file__).parent / "results_ga"
OUTPUT_DIR = Path(__file__).parent / "analysis_ga"
OUTPUT_DIR.mkdir(exist_ok=True)

TIMEOUT_S = 3600  # 1 hour

plt.rcParams.update({
    "font.size": 10,
    "axes.titlesize": 11,
    "axes.labelsize": 10,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "text.usetex": False,
    "font.family": "serif",
})

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_all_stats(results_dir: Path) -> pd.DataFrame:
    """Load all *_ga_default_stats.csv files into a single DataFrame."""
    rows = []
    for f in sorted(results_dir.glob("*_ga_default_stats.csv")):
        m = re.search(r"_o(\d+)_f(\d+)_s(\d+)_", f.name)
        if not m:
            continue
        df = pd.read_csv(f)
        df["objects"] = int(m.group(1))
        df["frames"] = int(m.group(2))
        df["scenario"] = int(m.group(3))
        rows.append(df)
    data = pd.concat(rows, ignore_index=True)
    data["instance_size"] = data["objects"] * data["frames"]
    data["timed_out"] = data["status"] != "SOLVED"
    return data


# ---------------------------------------------------------------------------
# Table generation
# ---------------------------------------------------------------------------

def format_time(seconds):
    """Format seconds for display."""
    if pd.isna(seconds):
        return "—"
    if seconds < 60:
        return f"{seconds:.1f}s"
    if seconds < 3600:
        return f"{seconds / 60:.1f}m"
    return f"{seconds / 3600:.1f}h"


def make_summary(data: pd.DataFrame) -> pd.DataFrame:
    """Per (objects, frames): mean solve time, number solved/timed-out."""
    grp = data.groupby(["objects", "frames"]).agg(
        n_runs=("status", "count"),
        n_solved=("timed_out", lambda x: (~x).sum()),
        n_timeout=("timed_out", "sum"),
        mean_time_s=("solve_time_seconds", "mean"),
        min_time_s=("solve_time_seconds", "min"),
        max_time_s=("solve_time_seconds", "max"),
    ).reset_index()
    grp["instance_size"] = grp["objects"] * grp["frames"]
    # For solved-only stats
    solved = data[~data["timed_out"]]
    if not solved.empty:
        solved_grp = solved.groupby(["objects", "frames"]).agg(
            mean_solved_s=("solve_time_seconds", "mean"),
        ).reset_index()
        grp = grp.merge(solved_grp, on=["objects", "frames"], how="left")
    else:
        grp["mean_solved_s"] = np.nan
    return grp.sort_values("instance_size")


def print_summary(summary: pd.DataFrame):
    """Print summary table to stdout."""
    print("\n" + "=" * 90)
    print("GA SOLVER — SOLVE TIME BY INSTANCE SIZE")
    print("=" * 90)
    print(f"{'Objects':>7} {'Frames':>6} {'Size':>6} {'Runs':>4} "
          f"{'Solved':>6} {'Timeout':>7} {'Mean time':>10} {'Min':>10} {'Max':>10}")
    print("-" * 90)
    for _, r in summary.iterrows():
        print(f"{int(r['objects']):>7} {int(r['frames']):>6} {int(r['instance_size']):>6} "
              f"{int(r['n_runs']):>4} {int(r['n_solved']):>6} {int(r['n_timeout']):>7} "
              f"{format_time(r['mean_time_s']):>10} {format_time(r['min_time_s']):>10} "
              f"{format_time(r['max_time_s']):>10}")


def write_latex_table(summary: pd.DataFrame, outdir: Path):
    """Write LaTeX table."""
    with open(outdir / "table_ga_solve_times.tex", "w") as f:
        f.write("% Auto-generated by analyze_ga.py\n")
        f.write("\\begin{table}[htbp]\n")
        f.write("\\centering\n")
        f.write("\\caption{GA solver: solve time by instance configuration. "
                "Timeout is 1\\,h.}\n")
        f.write("\\label{tab:ga_solve_times}\n")
        f.write("\\small\n")
        f.write("\\begin{tabular}{rrrrrr}\n")
        f.write("\\toprule\n")
        f.write("Obj & Fr & Size & Runs & Solved & Mean time (s) \\\\\n")
        f.write("\\midrule\n")
        for _, r in summary.iterrows():
            mean_str = (f"{r['mean_time_s']:.1f}" if r['mean_time_s'] < 100
                        else f"{r['mean_time_s']:.0f}")
            vals = [
                str(int(r["objects"])),
                str(int(r["frames"])),
                str(int(r["instance_size"])),
                str(int(r["n_runs"])),
                f"{int(r['n_solved'])}/{int(r['n_runs'])}",
                mean_str,
            ]
            f.write(" & ".join(vals) + " \\\\\n")
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
        f.write("\\end{table}\n")
    print(f"  -> table_ga_solve_times.tex")


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def plot_solve_time_by_objects(summary: pd.DataFrame, outdir: Path):
    """Line plot: solve time vs frames, one line per #objects."""
    obj_vals = sorted(summary["objects"].unique())
    markers = ["o", "s", "^", "D", "v", "P", "X"]

    fig, ax = plt.subplots(figsize=(9, 5.5))
    for oi, n_obj in enumerate(obj_vals):
        sub = summary[summary["objects"] == n_obj].sort_values("frames")
        color = plt.cm.tab10(oi / max(len(obj_vals) - 1, 1))
        marker = markers[oi % len(markers)]

        ax.plot(
            sub["frames"], sub["mean_time_s"],
            f"{marker}-",
            color=color,
            label=f"{n_obj} objects",
            markersize=5, alpha=0.8,
        )
        # Mark timeouts with open markers
        timed_out = sub[sub["n_solved"] == 0]
        if not timed_out.empty:
            ax.scatter(
                timed_out["frames"], timed_out["mean_time_s"],
                marker=marker, s=60, facecolors="none",
                edgecolors=color, linewidths=1.5, zorder=5,
            )

    ax.axhline(TIMEOUT_S, color="red", ls="--", alpha=0.5, label="Timeout (1 h)")
    ax.set_xlabel("Frames")
    ax.set_ylabel("Mean solve time (s)")
    ax.set_yscale("log")
    ax.set_title("GA solver: solve time vs. frames\n(open markers = all runs timed out)")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(outdir / "ga_solve_time_by_objects.pdf")
    fig.savefig(outdir / "ga_solve_time_by_objects.png")
    plt.close(fig)
    print(f"  -> ga_solve_time_by_objects.{{pdf,png}}")


def plot_solve_time_vs_size(summary: pd.DataFrame, outdir: Path):
    """Scatter/line plot: solve time vs instance size."""
    fig, ax = plt.subplots(figsize=(9, 5.5))

    solved = summary[summary["n_solved"] > 0]
    timeout = summary[summary["n_solved"] == 0]

    if not solved.empty:
        ax.scatter(
            solved["instance_size"], solved["mean_time_s"],
            c="tab:blue", marker="o", s=40, label="Solved", zorder=5,
        )
    if not timeout.empty:
        ax.scatter(
            timeout["instance_size"], timeout["mean_time_s"],
            c="tab:red", marker="x", s=40, label="Timed out", alpha=0.6, zorder=4,
        )

    ax.axhline(TIMEOUT_S, color="red", ls="--", alpha=0.5, label="Timeout (1 h)")
    ax.set_xlabel("Instance size (objects × frames)")
    ax.set_ylabel("Mean solve time (s)")
    ax.set_yscale("log")
    ax.set_title("GA solver: solve time vs. instance size")
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(outdir / "ga_solve_time_vs_size.pdf")
    fig.savefig(outdir / "ga_solve_time_vs_size.png")
    plt.close(fig)
    print(f"  -> ga_solve_time_vs_size.{{pdf,png}}")


def plot_heatmap(summary: pd.DataFrame, outdir: Path):
    """Heatmap of mean solve time: rows=objects, cols=frames."""
    from matplotlib.colors import LogNorm

    obj_vals = sorted(summary["objects"].unique())
    frame_vals = sorted(summary["frames"].unique())

    pvt = summary.pivot_table(index="objects", columns="frames", values="mean_time_s")
    pvt = pvt.reindex(index=obj_vals, columns=frame_vals)

    fig, ax = plt.subplots(figsize=(8, 5))
    vmin = max(pvt.values[~np.isnan(pvt.values)].min(), 0.1)
    vmax = pvt.values[~np.isnan(pvt.values)].max()
    im = ax.imshow(
        pvt.values,
        aspect="auto",
        norm=LogNorm(vmin=vmin, vmax=vmax),
        cmap="YlOrRd",
        origin="lower",
    )
    ax.set_xticks(range(len(frame_vals)))
    ax.set_xticklabels(frame_vals, rotation=45, ha="right")
    ax.set_yticks(range(len(obj_vals)))
    ax.set_yticklabels(obj_vals)
    ax.set_xlabel("Frames")
    ax.set_ylabel("Objects")
    ax.set_title("GA solver: mean solve time")

    for i in range(len(obj_vals)):
        for j in range(len(frame_vals)):
            val = pvt.values[i, j]
            if not np.isnan(val):
                txt = format_time(val)
                color = "white" if val > (vmax * 0.3) else "black"
                ax.text(j, i, txt, ha="center", va="center", fontsize=6, color=color)

    fig.colorbar(im, ax=ax, label="Solve time (s)")
    fig.tight_layout()
    fig.savefig(outdir / "ga_heatmap_solve_time.pdf")
    fig.savefig(outdir / "ga_heatmap_solve_time.png")
    plt.close(fig)
    print(f"  -> ga_heatmap_solve_time.{{pdf,png}}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print(f"Loading data from {RESULTS_DIR} ...")
    data = load_all_stats(RESULTS_DIR)
    print(f"  Loaded {len(data)} rows")
    print(f"  Objects: {sorted(data['objects'].unique())}")
    print(f"  Frames:  {sorted(data['frames'].unique())}")
    print(f"  Status:  {data['status'].value_counts().to_dict()}")

    summary = make_summary(data)
    print_summary(summary)

    # Write outputs
    summary.to_csv(OUTPUT_DIR / "summary_ga_solve_times.csv", index=False)
    write_latex_table(summary, OUTPUT_DIR)

    print("\nGenerating plots...")
    plot_solve_time_by_objects(summary, OUTPUT_DIR)
    plot_solve_time_vs_size(summary, OUTPUT_DIR)
    plot_heatmap(summary, OUTPUT_DIR)

    print(f"\nAll outputs written to {OUTPUT_DIR}/")
    print("Done.")


if __name__ == "__main__":
    main()
